import { test, expect } from '@playwright/test';

test('dist: Projekt-Roundtrip erhält Trasse, Wärmegraph und legitime Nullwerte', async ({ page }) => {
  const pageErrors = [];
  page.on('pageerror', error => pageErrors.push(String(error)));
  await page.route(/tile\.openstreetmap\.org/, route => route.abort());
  await page.goto('/');
  await page.waitForFunction(() => typeof window._buildProjectData === 'function' && typeof window._loadProject === 'function');

  const result = await page.evaluate(() => {
    const fixture = _buildProjectData();
    fixture.gebaeude = [];
    fixture.netz = {
      ...fixture.netz,
      zentrale: '',
      v: 0,
      tAussen: 0,
      tMittel: 0,
      uWert: 0,
      gzfMethode: 'manuell',
      gzfManuell: 0,
      isLocked: false,
    };
    fixture.trasse = [
      {lat: 52.081, lng: 8.003},
      {lat: 52.082, lng: 8.004},
      {lat: 52.083, lng: 8.005},
    ];
    fixture.trasseSegments = [{start: 0, end: 2, domains: ['waerme']}];
    fixture.waermeNetzGraph = {
      nodes: [
        {id: 10001, type: 'junction', lat: 52.081, lng: 8.003, load: 0},
        {id: 10002, type: 'junction', lat: 52.083, lng: 8.005, load: 0},
      ],
      edges: [{u: 10001, v: 10002, dn: 0, pruned: false, kostKlasse: null, kostOverride: false,
        waypoints: [{lat: 52.0817, lng: 8.0036}, {lat: 52.0824, lng: 8.0043}],
        waypoint: {lat: 52.0817, lng: 8.0036}}],
    };
    fixture.stromNetz = {nodes:[], edges:[], kabelTyp:'NAYY'};
    fixture.pvPanel = {...fixture.pvPanel, kwp:'40', vergModell:'teil', tarifSzenario:'de-eeg-2026-02-01', einspeisung:'99'};
    fixture.pvProfile = {values:Array.from({length:8760}, (_, i) => i === 8759 ? 1.25 : 0),
      meta:{quality:'modeled_external',source:'European Commission JRC PVGIS',filename:'roundtrip-pvgis.csv',unit:'kWh/h'}};
    fixture.economicScenario = {
      scenarioId:'manual', provenance:{scenarioId:'manual', manualOverrides:true},
      values:{stromCtKwh:0,wpStromCtKwh:null,gasCtKwh:7.25,heizoelCtKwh:11,fernwaermeCtKwh:16,
        pelletsCtKwh:8.5,hhsCtKwh:5.5,co2EurT:0,co2Alle:false,kapitalzinsPct:0,lohnEurH:55},
    };
    fixture.battery = {capacityKwh:100,powerKw:50,investEurKwh:375,studyLifeYears:18,
      calendarFadePctPerYear:1.2,cycleLife:7000,eolCapacityPct:75,aging:null};
    fixture.elektroAssets = {
      items: [
        {id:'nap_roundtrip', type:'NAP', domain:'strom', lat:52.081, lng:8.006, name:'NAP Test', props:{leistungKVA:630}, massnahmen:[]},
        {id:'sa_roundtrip', type:'Schaltanlage', domain:'strom', lat:52.082, lng:8.007, name:'SA Test', props:{felder:4}, massnahmen:[]},
      ],
      edges: [{id:'edge_roundtrip', u:'nap_roundtrip', v:'sa_roundtrip', cableType:'NA2XS2Y', crossSection:0,
        autoSized:false, lengthM:125, fuseA:0, nParallel:1, autoGenerated:false, msLevel:true, trennstelle:true,
        baujahr:2025, abrissjahr:null, massnahmen:[{id:'m_roundtrip', typ:'Austausch', status:'geplant'}]}],
    };

    _loadProject(fixture);
    const automaticTariff = document.getElementById('strom-preis-einsp').value;
    document.getElementById('strom-preis-einsp').readOnly = false;
    document.getElementById('strom-preis-einsp').value = '4.44';
    onPvTariffManualInput();
    const editableEdge = window.netzEdges[0];
    editableEdge.midMarker.setLatLng(L.latLng(52.0828, 8.0047));
    editableEdge.midMarker.fire('dragend');
    const exported = _buildProjectData();

    setTrassePoints([]);
    setTrasseSegments([]);
    clearNetz();
    document.getElementById('netz-v').value = 9;
    _loadProject(exported);
    const restored = _buildProjectData();

    return {
      trasse: restored.trasse,
      segments: restored.trasseSegments,
      graph: restored.waermeNetzGraph,
      zeroValues: {
        v: restored.netz.v,
        tAussen: restored.netz.tAussen,
        tMittel: restored.netz.tMittel,
        uWert: restored.netz.uWert,
        gzfManuell: restored.netz.gzfManuell,
      },
      manifest: {
        version: restored.calculationManifest?.manifestVersion,
        appVersion: restored.calculationManifest?.appVersion,
        optimizerMethod: restored.calculationManifest?.models?.optimizer?.method,
        limitations: restored.calculationManifest?.limitations?.length,
        tariffScenario: restored.calculationManifest?.dataQuality?.pvTariff?.scenarioId,
      },
      tariff: {
        automaticTariff,
        restoredRate: restored.pvPanel.einspeisung,
        restoredModel: restored.pvPanel.vergModell,
        restoredScenario: restored.pvPanel.tarifSzenario,
      },
      economics: restored.economicScenario,
      pvProfile: {length:restored.pvProfile?.values?.length,first:restored.pvProfile?.values?.[0],last:restored.pvProfile?.values?.[8759],meta:restored.pvProfile?.meta,
        manifestQuality:restored.calculationManifest?.dataQuality?.pvProfile?.quality},
      battery: restored.battery,
      electric: {
        items: restored.elektroAssets.items
          .filter(item => item.id.endsWith('_roundtrip'))
          .map(item => ({id:item.id, type:item.type, name:item.name, props:item.props})),
        edges: restored.elektroAssets.edges
          .filter(edge => edge.id === 'edge_roundtrip')
          .map(edge => ({id:edge.id, u:edge.u, v:edge.v, crossSection:edge.crossSection,
            autoSized:edge.autoSized, fuseA:edge.fuseA, msLevel:edge.msLevel, trennstelle:edge.trennstelle,
            baujahr:edge.baujahr, abrissjahr:edge.abrissjahr, massnahmen:edge.massnahmen})),
      },
    };
  });

  expect(result.trasse).toEqual([
    {lat: 52.081, lng: 8.003},
    {lat: 52.082, lng: 8.004},
    {lat: 52.083, lng: 8.005},
  ]);
  expect(result.segments).toEqual([{start: 0, end: 2, domains: ['waerme']}]);
  expect(result.graph.edges).toEqual([
    {u: 10001, v: 10002, dn: 0, pruned: false, kostKlasse: null, kostOverride: false,
      waypoints: [
        {lat: 52.0817, lng: 8.0036},
        {lat: 52.0824, lng: 8.0043},
        {lat: 52.0828, lng: 8.0047},
      ],
      waypoint: {lat: 52.0817, lng: 8.0036}},
  ]);
  expect(Object.values(result.zeroValues).map(Number)).toEqual([0, 0, 0, 0, 0]);
  expect(result.manifest.version).toBe(1);
  expect(result.manifest.appVersion).toMatch(/^(0\.1\.0|dev)$/);
  expect(result.manifest.optimizerMethod).toMatch(/heuristisch/i);
  expect(result.manifest.limitations).toBeGreaterThanOrEqual(4);
  expect(Number(result.tariff.automaticTariff)).toBeCloseTo(6.99, 2);
  expect(result.tariff).toEqual({automaticTariff:'6.99', restoredRate:'4.44', restoredModel:'manuell', restoredScenario:'manual'});
  expect(result.manifest.tariffScenario).toBe('manual');
  expect(result.economics.scenarioId).toBe('manual');
  expect(result.economics.values).toEqual({stromCtKwh:0,wpStromCtKwh:null,gasCtKwh:7.25,heizoelCtKwh:11,
    fernwaermeCtKwh:16,pelletsCtKwh:8.5,hhsCtKwh:5.5,co2EurT:0,co2Alle:false,kapitalzinsPct:0,lohnEurH:55});
  expect(result.economics.provenance.manualOverrides).toBe(true);
  expect(result.pvProfile.length).toBe(8760);
  expect([result.pvProfile.first,result.pvProfile.last]).toEqual([0,1.25]);
  expect(result.pvProfile.meta).toMatchObject({quality:'modeled_external',source:'European Commission JRC PVGIS',filename:'roundtrip-pvgis.csv',unit:'kWh/h'});
  expect(result.pvProfile.manifestQuality).toBe('modeled_external');
  expect(result.battery).toMatchObject({capacityKwh:100,powerKw:50,investEurKwh:375,studyLifeYears:18,
    calendarFadePctPerYear:1.2,cycleLife:7000,eolCapacityPct:75});
  expect(result.electric.items).toEqual([
    {id:'nap_roundtrip', type:'NAP', name:'NAP Test', props:{leistungKVA:630}},
    {id:'sa_roundtrip', type:'Schaltanlage', name:'SA Test', props:{felder:4}},
  ]);
  expect(result.electric.edges).toEqual([{
    id:'edge_roundtrip', u:'nap_roundtrip', v:'sa_roundtrip', crossSection:0,
    autoSized:false, fuseA:0, msLevel:true, trennstelle:true, baujahr:2025, abrissjahr:null,
    massnahmen:[{id:'m_roundtrip', typ:'Austausch', status:'geplant'}],
  }]);
  expect(pageErrors).toHaveLength(0);
});
